# Generated by Django 4.2 on 2023-05-03 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0007_profilelikes_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_avatar', models.ImageField(blank=True, null=True, upload_to='chats/avatars')),
                ('member_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_one', to='Profile.profiledata')),
                ('member_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_two', to='Profile.profiledata')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('uploaded_image', models.FileField(blank=True, null=True, upload_to='chats/message_pictures')),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Chat.chat')),
            ],
        ),
    ]
