# Generated by Django 4.2 on 2023-05-29 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0010_alter_profiledata_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('uploaded_image', models.FileField(blank=True, null=True, upload_to='chats/message_pictures/%Y/%m/%d/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Profile.profiledata')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('member_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_one', to='Profile.profiledata')),
                ('member_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_two', to='Profile.profiledata')),
                ('messages', models.ManyToManyField(blank=True, to='Chat.message')),
            ],
        ),
    ]
