# Generated by Django 4.2 on 2023-05-03 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='member_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_one', to='Profile.profiledata'),
        ),
        migrations.AddField(
            model_name='chat',
            name='member_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_two', to='Profile.profiledata'),
        ),
    ]
