# Generated by Django 4.2 on 2023-05-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_message_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='uploaded_image',
            field=models.FileField(blank=True, null=True, upload_to='chats/message_pictures/%Y/%m/%d/'),
        ),
    ]
