# Generated by Django 4.2 on 2023-05-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledata',
            name='couples_requests',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profiledata',
            name='current_сouple_request',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
