# Generated by Django 4.2 on 2023-05-05 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_profiledata_couples_requests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledata',
            name='current_сouple_request',
        ),
        migrations.RemoveField(
            model_name='profiledata',
            name='interests',
        ),
        migrations.AddField(
            model_name='profiledata',
            name='about_you',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('1', 'single'), ('2', 'in-relations'), ('3', 'complicated')], max_length=1, null=True)),
                ('purpose', models.CharField(blank=True, choices=[('1', 'serious'), ('2', 'non-serious'), ('3', 'just-for-fun'), ('4', 'short-period'), ('5', 'long-period'), ('6', 'acquintances')], max_length=1, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('drinking', models.CharField(blank=True, choices=[('1', 'sometimes'), ('2', 'rarely'), ('3', 'never')], max_length=1, null=True)),
                ('smoking', models.CharField(blank=True, choices=[('1', 'yes'), ('2', 'sometimes'), ('3', 'vape'), ('4', 'no')], max_length=1, null=True)),
                ('sport', models.CharField(blank=True, choices=[('1', 'always'), ('2', 'sometimes'), ('3', 'rarely'), ('4', 'never')], max_length=1, null=True)),
                ('children', models.CharField(blank=True, choices=[('1', 'already-have'), ('2', 'dont-have-but-want'), ('3', 'dont-have'), ('4', 'childfree')], max_length=1, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.profiledata')),
            ],
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music', models.BooleanField(blank=True, null=True)),
                ('travelling', models.BooleanField(blank=True, null=True)),
                ('fashion', models.BooleanField(blank=True, null=True)),
                ('hiking', models.BooleanField(blank=True, null=True)),
                ('photographing', models.BooleanField(blank=True, null=True)),
                ('parties_clubs', models.BooleanField(blank=True, null=True)),
                ('art', models.BooleanField(blank=True, null=True)),
                ('meditation', models.BooleanField(blank=True, null=True)),
                ('football', models.BooleanField(blank=True, null=True)),
                ('fishing_hunting', models.BooleanField(blank=True, null=True)),
                ('running', models.BooleanField(blank=True, null=True)),
                ('swimming', models.BooleanField(blank=True, null=True)),
                ('cooking', models.BooleanField(blank=True, null=True)),
                ('shoping', models.BooleanField(blank=True, null=True)),
                ('restaurants', models.BooleanField(blank=True, null=True)),
                ('cinema', models.BooleanField(blank=True, null=True)),
                ('board_games', models.BooleanField(blank=True, null=True)),
                ('blogging', models.BooleanField(blank=True, null=True)),
                ('it', models.BooleanField(blank=True, null=True)),
                ('dancing', models.BooleanField(blank=True, null=True)),
                ('sport', models.BooleanField(blank=True, null=True)),
                ('creativity', models.BooleanField(blank=True, null=True)),
                ('books', models.BooleanField(blank=True, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.profiledata')),
            ],
        ),
    ]
