# Generated by Django 4.2 on 2023-05-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_profilelikes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilelikes',
            old_name='likes',
            new_name='like',
        ),
        migrations.AddField(
            model_name='profilelikes',
            name='liker',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
