# Generated by Django 4.2 on 2023-05-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_rename_likes_profilelikes_like_profilelikes_liker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilelikes',
            old_name='liker',
            new_name='likerid',
        ),
    ]
