# Generated by Django 4.2 on 2023-05-05 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_remove_profiledata_current_сouple_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interests',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='personaldata',
            name='profile',
        ),
        migrations.AddField(
            model_name='profiledata',
            name='interests',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.interests'),
        ),
        migrations.AddField(
            model_name='profiledata',
            name='personal_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.personaldata'),
        ),
    ]
