# Generated by Django 4.2 on 2023-05-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_rename_liker_profilelikes_likerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledata',
            name='acquaintances_available',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
