# Generated by Django 4.2 on 2023-05-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_remove_interests_profile_remove_personaldata_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='children',
            field=models.CharField(blank=True, choices=[('Уже есть', 'already-have'), ('Нет, но хочу', 'dont-have-but-want'), ('Нет', 'dont-have'), ('Чайлдфри', 'childfree')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='drinking',
            field=models.CharField(blank=True, choices=[('Иногда', 'sometimes'), ('Редко', 'rarely'), ('Никогда', 'never')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='purpose',
            field=models.CharField(blank=True, choices=[('Серьзные отношения', 'serious'), ('Свободные отношения', 'non-serious'), ('Для развлечений', 'just-for-fun'), ('Временные', 'short-period'), ('Постоянные', 'long-period'), ('Отношения', 'acquintances')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='smoking',
            field=models.CharField(blank=True, choices=[('Курю', 'yes'), ('Редко курю', 'sometimes'), ('Парю', 'vape'), ('Не курю и не парю', 'no')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='sport',
            field=models.CharField(blank=True, choices=[('Постоянно', 'always'), ('Иногда', 'sometimes'), ('Редко', 'rarely'), ('Никогда', 'never')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='status',
            field=models.CharField(blank=True, choices=[('Не в отношениях', 'single'), ('В отношениях', 'in-relations'), ('Все сложно', 'complicated')], max_length=100, null=True),
        ),
    ]
