# Generated by Django 4.2 on 2023-05-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_alter_personaldata_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='children',
            field=models.CharField(blank=True, choices=[('Уже есть', 'Уже есть'), ('Нет, но хочу', 'Нет, но хочу'), ('Нет', 'Нет'), ('Чайлдфри', 'Чайлдфри')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='drinking',
            field=models.CharField(blank=True, choices=[('Иногда', 'Иногда'), ('Редко', 'Редко'), ('Никогда', 'Никогда')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='purpose',
            field=models.CharField(blank=True, choices=[('Серьзные отношения', 'Серьзные отношения'), ('Свободные отношения', 'Свободные отношения'), ('Для развлечений', 'Для развлечений'), ('Временные', 'Временные'), ('Постоянные', 'Постоянные'), ('Отношения', 'Отношения')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='smoking',
            field=models.CharField(blank=True, choices=[('Курю', 'Курю'), ('Редко курю', 'Редко курю'), ('Парю', 'Парю'), ('Не курю и не парю', 'Не курю и не парю')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='sport',
            field=models.CharField(blank=True, choices=[('Постоянно', 'Постоянно'), ('Иногда', 'Иногда'), ('Редко', 'Редко'), ('Никогда', 'Никогда')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='status',
            field=models.CharField(blank=True, choices=[('Не в отношениях', 'Не в отношениях'), ('В отношениях', 'В отношениях'), ('Все сложно', 'Все сложно')], max_length=100, null=True),
        ),
    ]
