# Generated by Django 4.2 on 2023-05-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_profiledata_current_acquaintance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilelikes',
            name='message',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
