# Generated by Django 4.2 on 2023-05-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_alter_personaldata_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledata',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
