# Generated by Django 4.2 on 2023-05-07 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_alter_profiledata_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledata',
            name='sexualorientation',
        ),
    ]
