# Generated by Django 4.2 on 2023-05-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0008_remove_profiledata_sexualorientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledata',
            name='age',
            field=models.IntegerField(blank=True, default=18, null=True),
        ),
    ]
