# Generated by Django 4.2 on 2023-05-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0009_profiledata_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledata',
            name='avatar',
            field=models.ImageField(upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
