# Generated by Django 4.2 on 2023-05-31 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0010_alter_profiledata_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='height',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(140), django.core.validators.MaxValueValidator(250)]),
        ),
    ]
