# Generated by Django 4.2 on 2023-05-08 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0008_remove_profiledata_sexualorientation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_limit_lower', models.IntegerField(blank=True, default=18, null=True)),
                ('age_limit_upper', models.IntegerField(blank=True, default=100, null=True)),
                ('height_limit_lower', models.IntegerField(blank=True, default=140, null=True)),
                ('height_limit_upper', models.IntegerField(blank=True, default=220, null=True)),
                ('profile_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.profiledata')),
            ],
        ),
    ]
